steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--depth', '1', '--branch', 'develop', 'https://github.com/tchoate-bphc/keep-ahope', 'front-end-src']
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'front-end-src'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'front-end-src'
- name: 'busybox'
  args: ['mv', '-f', 'front-end-src/build', './front-end']
# Replace a token/placeholder in the deployment config yaml file with a build-time-generated base64-encoded random number.
# note that we need the shell to perform command substitution (which is why a shell is needed), before running sed.
- name: 'busybox'
  args: ['ash', '-c', 'sed -i s#%%mk_salt_value%%#$(head -c 48 /dev/urandom | base64)# ./app.standard.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.standard.yaml']
  # while the above two steps can be absorbed into the next step since the same (or a superset of, in the case of busybox)
  # Docker image is used, running them separately yields better logging.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', './post-deploy.sh']
  env:
  - 'BUILD_ID=$BUILD_ID'
  - 'PROJECT_ID=$PROJECT_ID'
timeout: '1600s'
